manifest:
  remotes:
    # ZMK official
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Your own repo
    - name: rileyhora
      url-base: https://github.com/rileyhora

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml

    # Your own zmk-config repository
    - name: zmk-config
      remote: rileyhora
      revision: main

  self:
    path: config
